import { Router } from "express";

const router = Router();

/**
 * GET /csrf-token
 * Returns the current session CSRF token.
 *
 * Note: token is generated by csrfInit middleware (session-bound).
 */
router.get("/csrf-token", (req, res) => {
  return res.json({ csrfToken: req.csrfToken ?? req.session?.csrfToken ?? null });
});

export default router;
